name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add hub https://Karanm5:$HF@huggingface.co/spaces/Karanm5/demo1
      
      - name: Push to Hugging Face
        env:
          HF: ${{ secrets.HF }}
        run: git push hub main:main -f
