
name: Sync to Hugging Face Hub

# Control when the workflow will run

on:
  #Trigger the workflow on push or pull request event but only to the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  #Allow you to run this flow manually from the action tab

  workflow_dispatch:

#A workflow run is made up of one or more jobs  that can run sequentially or in parallel

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
       env:
         HF: ${{ secrets.HF}}
       run: git remote add space https://huggingface.co/spaces/Karanm5/demo1
      - name: Push to hub
        env:
          HF: ${{ secrets.HF}}
        run: git push --force https://huggingface.co/spaces/Karanm5/demo1 main
