name: Sync to Hugging Face Hub

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Updated from v2 to v3
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # More standard naming
        run: |
          git remote add space https://HF_TOKEN@huggingface.co/spaces/Karanm5/demo1
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://user:$HF_TOKEN@huggingface.co/spaces/Karanm5/demo1 main
